//============================================================
// this file was autogenerated by gen-ms-tables.py
// source file: EThrottleTables.csv
// date/time: 2025/11/22 10:45:00
//============================================================
#include "EThrottleTables.h"

OutPC_T outPC;
TestPage_T testPage;
