//============================================================
// this file was autogenerated by gen-ms-tables.py
// source file: EThrottleTables.csv
// date/time: 2025/10/26 08:11:59
//============================================================
#include "EThrottleTables.h"

OutPC_T outPC;
